Structs scaffolding
onelocom/onelo pull request #24
Opened 2020-09-22 19:10 UTC by israelfenor

Hi @arnau check this commit. Look context struct and implementation mainly. Are you agree about to have a new method to create a default values struct? Moreover I've added a version data using clap crate, it's ok? Regarding commit_hash I'm still working on it, I have thought find out some way to get the current git commit hash (maybe some crate could help me) automatically (like version)

2020-09-23 06:28 UTC, arnau requested changes
I haven't used `git_info` but looks like a good shot

2020-09-23 06:28 UTC, arnau commented on src/content_type.rs
> +}
I would say you could instead use:

```rust
pub struct ContentType(String);
```

And then, we can keep the implementation details hidden:

```rust
impl ContentType {
    pub fn new(id: String) -> Self {
        ContentType(String)
    }
}
```

2020-09-23 06:38 UTC, arnau commented on src/content_type.rs
> +}
Thinking about it, I think it's going to be better to use an enum, something like:

```rust
pub enum ContentType {
    Markdown,
    Other(String),
}
```

This way, once we have the content type identified and casted, we can match against it at the type level. The `Other` branch is for enabling extension in case we want some flexibility.

2020-09-23 15:23 UTC, israelfenor commented on src/content_type.rs
> +}
The turn of the screw :)

2020-09-26 10:05 UTC, arnau approved these changes

2020-09-27 10:33 UTC, merged